### ISSUE TITLE
Adding individual tracks from playlists

### ISSUE THREAD

**Issue by lovrolu** [rain0r/ampd#109]
It would be nice if you could add individual tracks from a playlist to the queue.

Currently, the browser only allows you to view and add the whole playlist, and clicking on a particular track from the playlist doesn't do anything.

**Comment by rain0r** [comment]
Hi there,

that's a good idea! I implemented it in aff393651ad52bcfb2ca10e66fef745d028e0629.

There's now an `add` and `play` button in the playlist modal.

**Comment by lovrolu** [comment]
Thanks for implementing it so quickly!

There are two small inconsistencies with the rest of the UI that I noticed:

(1) You can't just click anywhere on the item (other than the add or play buttons, of course) in order to add it to the play queue, like you can e.g. in the directory view

(2) When clicking on either the add or play buttons, you don't get a small notification at the bottom like you do when adding whole playlists or adding/playing songs from the directory view

**Comment by rain0r** [comment]
Hi there,

to 1:

A click on the row in the playlist info now adds the track to the queue. This behaviour is now the same as in the search view (or when viewing a directory). Thanks!

to 2:

Notifications after adding / playing a track is now in master: 6938d9602537ef1172e15a0cb2dafd400b8682f7

**Comment by lovrolu** [comment]
Works perfectly!

Thanks so much for your work and for the lightning fast responses! :-)
