### ISSUE TITLE
Is there merit to making ampd a Volumio/Moode plugin?

### ISSUE THREAD

**Issue by ibex-are-goats** [rain0r/ampd#13]
First off, great work!

I don't like the Volumio/Moode interfaces. Behind the times compared to yours. I suspect this interface can run on an Rpi. Is there merit to making ampd easily installable on those distros, perhaps like a Volumio plugin? Thanks for your answer :)

**Comment by rain0r** [comment]
Hi there,

thanks!

I'm sorry, but I don't know Volumio/Moode so I can't say anything about the possibility of creating a plugin for those.

However, `ampd` can run on Raspberries without problems. You only need a Java 11-runtime. 

As for the installation: just download the `jar` file from the releases and run it - no installation needed. ;-)

**Comment by ibex-are-goats** [comment]
Thank you for your reply! I'm happy to introduce you to something new ;) Your work is great, thank you again!

**Comment by rain0r** [comment]
Thanks :-) I'm closing this ticket now.
