### ISSUE TITLE
mpd server with password

### ISSUE THREAD

**Issue by Uriel12** [rain0r/ampd#3]
Hello,

i wanted to ask if you intend to support mpd-servers with passwords ?

I looked into your code and the underlying code base that you are using and it should be doable.

Personally my understanding of java is not perfect and I'm more of a beginner.
You should only need to change the code for the mpd builder or ?

So like this:
```
package org.hihn.ampd.server.config;

import org.bff.javampd.server.MPD;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MpdConfiguration {

  @Value("${mpd.server}")
  private String mpdServer;

  @Value("${mpd.port}")
  private int mpdPort;

  @Value("${mpd.password}")
  private String mpdPassword;

  public MPD mpd() {
    if(mpdPassword equals("")) {
         return new MPD.Builder().server(mpdServer).port(mpdPort).build();
    }
    else{
         return new MPD.Builder().server(mpdServer).port(mpdPort).password(mpdPassword).build():
   }
  }
}
```

Or am i completely wrong?

with regards

**Comment by rain0r** [comment]
Hi there, 

thanks for the suggestion and the proposed code. 
Password functionality is in release v1.0.4: https://github.com/rain0r/ampd/releases/tag/ampd-1.0.4
