### ISSUE TITLE
Browse => Album (empty)

### ISSUE THREAD

**Issue by Hippopoum** [rain0r/ampd#330]
Hi,
everything works fine except the album page which is empty.
I'm using mpd version 0.21.5-3 (raspberry), openjdk 11.0.15 2022-04-19 and ampd-1.4.5.

**Comment by rain0r** [comment]
Hi there,

thanks for filing this bug!

Can you provide me the content of the `ampd.log` file so I can examine the issue?

To help me even more, please start `ampd` with enhanced logging:

```sh
java -Dlogging.level.org.hihn.ampd=DEBUG -jar ampd-1.4.5.jar
``` 

And then provide me that output.

Thanks!

**Comment by Hippopoum** [comment]
If I put the following adress in my web browser: 192.168.0.50:1960/browse/albums

> I have this error message :
> "Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Mon Jun 27 10:19:26 CEST 2022
> There was an unexpected error (type=Not Found, status=404)."

**Comment by rain0r** [comment]
The reason for this error is, that your MPD versoin is just too old to use the features that are need for the album browse page - sorry.

Version 0.21.5 was released on February 22, 2019 so it may be a good idea to update it.

Maybe there is a ppa-repository with a newer version or you can build it yourself?

**Comment by rain0r** [comment]
> If I put the following adress in my web browser: 192.168.0.50:1960/browse/albums
> 
> > I have this error message :
> > "Whitelabel Error Page
> > This application has no explicit mapping for /error, so you are seeing this as a fallback.
> > Mon Jun 27 10:19:26 CEST 2022
> > There was an unexpected error (type=Not Found, status=404)."

This will be fixed in the next release. Thanks for reporting.

**Comment by Hippopoum** [comment]
The most recent version of Mpd provided by apt in Debian Buster is 0.21.5.3.
So I compiled version 0.23.5 and now everything works :)
Thank you very much from France!!

**Comment by rain0r** [comment]
Cool! I'm glad it's working.

Happy to help!
