### ISSUE TITLE
ampd 1.5.4 – search menu item is inactive

### ISSUE THREAD

**Issue by DirkSchmitt** [rain0r/ampd#414]
The menu item *Search* is now disabled.
In the last version 1.5.3 is has a minimal functionality.

**Comment by rain0r** [comment]
That's indeed a bug, thank you for reporting it.

Fixed in 6195821d93e7d5490cb86db732c2f1f23e6266c7.

**Comment by rain0r** [comment]
This is fixed in [1.5.5](https://github.com/rain0r/ampd/releases/tag/ampd-1.5.5).
