### ISSUE TITLE
Please improve search functionality.

### ISSUE THREAD

**Issue by DirkSchmitt** [rain0r/ampd#415]
The search capabilities in v 1.5.3 are very limited and expose only track search.

IMHO all type based queries should be supported in a favour as described in `man mpc`

       search <type> <query> [<type> <query>]... - Searches for
              substrings in song tags.  Any number of tag type and query combinations can be specified.  Possible tag types are: artist, album, title, track, name, genre, date,  composer,  performer,  com‐
              ment, disc, filename, or any (to match any tag).

Especially if the music library has a size of several thousand songs – in my case >100k – this is IMHO a very helpful feature.

**Comment by rain0r** [comment]
Agree, that would be a nice feature. 

This is something I will be working on.

**Comment by rain0r** [comment]
`ampd` now has an advanced search form. It can be accessed via the search dialog or directly via `/ampd/adv-search`.

Would be great to hear your feeedback on that. Hope, it's what your're looking for.

**Comment by DirkSchmitt** [comment]
Searching for artist 'Dylan', I'm getting the following error message:

    An error occurred

    [object Object]

    {
      "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
      },
      "status": 500,
      "statusText": "Internal Server Error",
      "url": "https://mpd.computer42.org/ampd/api/adv-search?album=&albumartist=&artist=dylan&title=&track=&genre=&date=&composer=&performer=&comment=c42&disc=&filename=",
      "ok": false,
      "name": "HttpErrorResponse",
      "message": "Http failure response for https://mpd.computer42.org/ampd/api/adv-search?album=&albumartist=&artist=dylan&title=&track=&genre=&date=&composer=&performer=&comment=c42&disc=&filename=: 500 Internal Server Error",
      "error": {
        "timestamp": 1668203844307,
        "status": 500,
        "error": "Internal Server Error",
        "path": "//api/adv-search"
      }
    }

**Comment by DirkSchmitt** [comment]
Stacktrace for this error:

    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]: 2022-11-12 22:07:42.515 ERROR 2634239 --- [.0-42080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: No cache could be resolved for 'Builder[public org.springframework.data.domain.PageImpl org.hihn.ampd.server.service.SearchService.search(java.util.Map,int)] caches=[] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'' using resolver 'org.springframework.cache.interceptor.SimpleCacheResolver@65d374d8'. At least one cache should be provided per cache operation.] with root cause
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]: java.lang.IllegalStateException: No cache could be resolved for 'Builder[public org.springframework.data.domain.PageImpl org.hihn.ampd.server.service.SearchService.search(java.util.Map,int)] caches=[] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'' using resolver 'org.springframework.cache.interceptor.SimpleCacheResolver@65d374d8'. At least one cache should be provided per cache operation.
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:255) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.<init>(CacheAspectSupport.java:724) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.getOperationContext(CacheAspectSupport.java:265) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts.<init>(CacheAspectSupport.java:615) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.hihn.ampd.server.service.SearchService$$EnhancerBySpringCGLIB$$c3bd3a12.search(<generated>) ~[classes!/:1.5.6]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.hihn.ampd.server.controller.AdvSearchController.search(AdvSearchController.java:29) ~[classes!/:1.5.6]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]: 2022-11-12 22:07:42.515 ERROR 2634239 --- [.0-42080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: No cache could be resolved for 'Builder[public org.springframework.data.domain.PageImpl org.hihn.ampd.server.service.SearchService.search(java.util.Map,int)] caches=[] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'' using resolver 'org.springframework.cache.interceptor.SimpleCacheResolver@65d374d8'. At least one cache should be provided per cache operation.] with root cause
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]: java.lang.IllegalStateException: No cache could be resolved for 'Builder[public org.springframework.data.domain.PageImpl org.hihn.ampd.server.service.SearchService.search(java.util.Map,int)] caches=[] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'' using resolver 'org.springframework.cache.interceptor.SimpleCacheResolver@65d374d8'. At least one cache should be provided per cache operation.
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:255) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.<init>(CacheAspectSupport.java:724) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.getOperationContext(CacheAspectSupport.java:265) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts.<init>(CacheAspectSupport.java:615) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64) ~[spring-context-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.hihn.ampd.server.service.SearchService$$EnhancerBySpringCGLIB$$c3bd3a12.search(<generated>) ~[classes!/:1.5.6]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.hihn.ampd.server.controller.AdvSearchController.search(AdvSearchController.java:29) ~[classes!/:1.5.6]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar!/:5.3.23]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.68.jar!/:na]
    Sat 2022-11-12 22:07:42 CET ampd.service[2634239]:         at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

~

**Comment by rain0r** [comment]
Hi there!

Sorry for the late anweser.

I started to work on this issue which started a knock-on effect. 

However, this should all be fixed in the release [ampd-1.5.7](https://github.com/rain0r/ampd/releases/tag/ampd-1.5.7).

I would be glad to hear your feedback on it!

**Comment by rain0r** [comment]
Closing this as it's working.
