### ISSUE TITLE
Request: move https and backend configuration to ampd.conf

### ISSUE THREAD

**Issue by snflh47** [rain0r/ampd#51]
I have tested ampd for a couple of days now and really like it as an mpd client.

There's just some small usability-issues with ampd:

In my use case, i don't want to run ampd locally (client) but on the same machine that runs mpd, making the controls available to any device on the network. I would very much appreciate the ampd.conf to include parameters for the backend address and https on/off options. As of now, it seems these options need to be set while building (properties in pom.xml), making a custom build necessary. If these parameters were saved in ampd.conf, it would be possible to send them to the browser's storage automatically, so using a rather complicated address like "http://host.name/settings?backend=host.name" would not be necessary anymore.

Also running ampd through a reverse proxy to leverage https, authentication, etc.  is pretty complicated in the current state, as a https address can't be passed as URL parameter, due to the fact that there's a mechanism in (filename?) that prefixes it with http anyway.

Any chance to have these options in ampd.conf in the future? Maybe even keep the static values from the build and just override if defined in the ampd.conf?

Another small issue I had when running ampd through a reverse proxy is that I didn't succeed rewriting the paths to serve ampd through a URL like "https://host.name/ampd" because some files seem to be pretty static in their referencing and expect to be found in "/". I guess changing this one would be some trouble, so that's not much of a concern right now.

**Comment by rain0r** [comment]
Hi there!

I will try and think about a solution for the problem with the backend address. Somehow, the address of the backend has to go to the frontend. The output of the message http://host.name/settings?backend=host.name was a handy workaround to save the backend address in the browser but it doesn't help if you want to access with your mobile phone. I guess I never stumbled upon this problem because I use custom builds in my home network (of course).

Also, you're right, ampd is not supposed to work with https. But I will address that issue, too. Until now, nobody seemed to miss that.

For your last problem, the reverse proxy. To run ampd under a directory other than `/`, it unfortunately needs to be build with a specific flag (`frontend.context` in the pom). This gets passed to the `base-href` parameter when building angular.

There are a few hacky solutions which didn't work for me / in my setup. I can give it one more try but it definitely is the lowest priority of these three. Anyway, if you ever build your own ampd, it's just `ProxyPass` and `ProxyPassReverse` in your apache config.

**Comment by snflh47** [comment]
Hi rain0r,

thanks for the fast reply!

Of course, the reverse proxy folder/path issue is of lowest priority, if you're willing to address this at all. I would surely understand if you find it's not necessary as it's a special use case.

What came to my mind when reading your answer: why not just use the requested URL (or maybe the SNI) as input instead of the "settings=backend=host.name" parameter and leave the rest as is? Or am I missing something here?

For the https part I'll gladly use a reverse proxy, no need to add anything to ampd, really. My problem was more of a conflict: running ampd proxied via https and passing the backend server address in the URL does not work due to the automatic "http" prefixing, so every time I open the application, manual fixing of the URL is needed.

Let me know if I can be of any help regarding some more input or testing.

**Comment by rain0r** [comment]
Hey there, long time no hear. I was quite busy last week with the realization of your requests and I have to say they brought me some headache. But mostly, because I was lazy in earlier stages of development, hehe. I used this chance to get a few things right which I delayed in the past. So, thanks for that, I think the code is now a little bit cleaner.

To your points, please see the release [ampd-1.2.8](https://github.com/rain0r/ampd/releases/tag/ampd-1.2.8)

- https works now (please see the README for a sample for Apache)
- No need to set the `backendAddr` manually. No matter if behind a proxy or not
- There are now two jar files per release, on for the context `/` and one for `/ampd/`

Check it out and let me know if that solves your problem and / or if you have any problems / suggestions.

Cheers

**Comment by snflh47** [comment]
Hi rain0r,

actually I didn't even expect this to happen so fast, so thanks a lot!

First things first: it worked right out of the box! The GUI seems even more responsive to me and I can control mpd flawlessly and of course browse and search the library. 

This is a usable state for me.

HTTPS is untested so far as I've just installed a new box with mpd and ampd. I will get to this some time later.

Now what I've noticed during startup: there seems to be a problem parsing the mpd.conf:

The music directory is not detected correctly (empty value, see log below), but playback is working fine so the config must be OK. This is an mpd in satellite configuration with a central mpd "server" being the backend for this ampd-controlled mpd. The local mpd.conf contains only one source, which is an nfs share:
`
music_directory "nfs://servername/shares/audio"`

```
2021-02-25 20:10:00.712  INFO 3057 --- [           main] org.hihn.ampd.server.ServerApplication   : No active profile set, falling back to default profiles: default
2021-02-25 20:10:06.835  INFO 3057 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-02-25 20:10:06.837  INFO 3057 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.43]
2021-02-25 20:10:06.926  INFO 3057 --- [           main] org.apache.catalina.loader.WebappLoader  : Unknown class loader [jdk.internal.loader.ClassLoaders$PlatformClassLoader@47ef5a33] of class [class jdk.internal.loader.ClassLoaders$PlatformClassLoader]
2021-02-25 20:10:07.088  INFO 3057 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-02-25 20:10:08.063  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mpdServer: localhost
2021-02-25 20:10:08.064  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : musicDirectory: 
2021-02-25 20:10:08.072  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mpdPort: 6600
```


Second thing I noticed is some error I don't understand either :)


```
2021-02-25 20:10:08.074  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : localCoverCache: true
2021-02-25 20:10:08.076  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mbCoverService: true
2021-02-25 20:10:08.080 ERROR 3057 --- [           main] o.h.a.server.service.CoverCacheService   : Could not create the MusicBrainz blacklist file: /home/username/.local/share/ampd/mb_blacklist.txt
2021-02-25 20:10:08.087  WARN 3057 --- [           main] o.h.a.s.service.CoverBlacklistService    : Could not load or create the Musicbrainz Cover blacklist file.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/username/.m2/repository/com/google/inject/guice/4.2.3/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-02-25 20:10:13.009  INFO 3057 --- [           main] org.hihn.ampd.server.ServerApplication   : Started ServerApplication in 14.814 seconds (JVM running for 69.429)
```


Something else I noticed during the first start of ampd but couldn't reproduce later (maybe I'd need to clean "~/.m2/..." first?) is some https connections to google popping up like 6 times? I'm not quite sure why ampd would do that?


Again, thanks so far! I will keep you updated on the https tests once I get to them.

**Comment by rain0r** [comment]
Hi there

> Hi rain0r,
> 
> actually I didn't even expect this to happen so fast, so thanks a lot!
> 
> First things first: it worked right out of the box! The GUI seems even more responsive to me and I can control mpd flawlessly and of course browse and search the library.

Thanks!

> 
> This is a usable state for me.
> 
> HTTPS is untested so far as I've just installed a new box with mpd and ampd. I will get to this some time later.
> 
> Now what I've noticed during startup: there seems to be a problem parsing the mpd.conf:
> 
> The music directory is not detected correctly (empty value, see log below), but playback is working fine so the config must be OK. This is an mpd in satellite configuration with a central mpd "server" being the backend for this ampd-controlled mpd. The local mpd.conf contains only one source, which is an nfs share:
> ` music_directory "nfs://servername/shares/audio"`

The music directory is only used to load the album covers, so it's not a big problem if `ampd` can't access it. The whole process playing/browsing music is done via MPD which functions over network. So no worries, if you like, `ampd` can download the covers from MusicBrainz (I see you got that setting active).

> 
> ```
> 2021-02-25 20:10:00.712  INFO 3057 --- [           main] org.hihn.ampd.server.ServerApplication   : No active profile set, falling back to default profiles: default
> 2021-02-25 20:10:06.835  INFO 3057 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2021-02-25 20:10:06.837  INFO 3057 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.43]
> 2021-02-25 20:10:06.926  INFO 3057 --- [           main] org.apache.catalina.loader.WebappLoader  : Unknown class loader [jdk.internal.loader.ClassLoaders$PlatformClassLoader@47ef5a33] of class [class jdk.internal.loader.ClassLoaders$PlatformClassLoader]
> 2021-02-25 20:10:07.088  INFO 3057 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2021-02-25 20:10:08.063  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mpdServer: localhost
> 2021-02-25 20:10:08.064  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : musicDirectory: 
> 2021-02-25 20:10:08.072  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mpdPort: 6600
> ```
> 
> Second thing I noticed is some error I don't understand either :)
> 
> ```
> 2021-02-25 20:10:08.074  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : localCoverCache: true
> 2021-02-25 20:10:08.076  WARN 3057 --- [           main] org.hihn.ampd.server.model.Settings      : mbCoverService: true
> 2021-02-25 20:10:08.080 ERROR 3057 --- [           main] o.h.a.server.service.CoverCacheService   : Could not create the MusicBrainz blacklist file: /home/username/.local/share/ampd/mb_blacklist.txt
> 2021-02-25 20:10:08.087  WARN 3057 --- [           main] o.h.a.s.service.CoverBlacklistService    : Could not load or create the Musicbrainz Cover blacklist file.
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/username/.m2/repository/com/google/inject/guice/4.2.3/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 2021-02-25 20:10:13.009  INFO 3057 --- [           main] org.hihn.ampd.server.ServerApplication   : Started ServerApplication in 14.814 seconds (JVM running for 69.429)
> ```
> 

Does this happen with the release jar of `ampd` or did you build it yourself? To be honest I never encountered this warning and a quick search led me to believe it's tedious but not breaking. Deleting `~/.m2/repository/` may help, but that's just a guess. Maybe try running `ampd` with another JRE version if you don't want to see it anymore.

> Something else I noticed during the first start of ampd but couldn't reproduce later (maybe I'd need to clean "~/.m2/..." first?) is some https connections to google popping up like 6 times? I'm not quite sure why ampd would do that?
> 

Uh, yes. `ampd` used connect via datagram socket to get the local network ip for the `If this is your first start, visit ...` link. I removed it completely in 5189df0af0bac431df9612f004b305ff43c914a4. Thanks for the hint.

> Again, thanks so far! I will keep you updated on the https tests once I get to them.

Thanks!

**Comment by rain0r** [comment]
> Uh, yes. `ampd` used connect via datagram socket to get the local network ip for the `If this is your first start, visit ...` link. I removed it completely in [5189df0](https://github.com/rain0r/ampd/commit/5189df0af0bac431df9612f004b305ff43c914a4). Thanks for the hint.

Version [1.2.9](https://github.com/rain0r/ampd/releases/tag/ampd-1.2.9) does not connect to google.

**Comment by snflh47** [comment]
> The music directory is only used to load the album covers, so it's not a big problem if `ampd` can't access it. The whole process playing/browsing music is done via MPD which functions over network. So no worries, if you like, `ampd` can download the covers from MusicBrainz (I see you got that setting active).

The covers are there, so accessing them locally would be nice, of course. If you can tell me how to produce better log output, there might be a hint on what's going wrong there. Or maybe nfs paths aren't supported at all yet?

> Does this happen with the release jar of `ampd` or did you build it yourself? To be honest I never encountered this warning and a quick search led me to believe it's tedious but not breaking. Deleting `~/.m2/repository/` may help, but that's just a guess. Maybe try running `ampd` with another JRE version if you don't want to see it anymore.

I used your release of "ampd-1.2.8.jar".

JRE is openjdk-14-jdk-headless from Ubuntu repositories. It was the same with openjdk-11-jdk-headless and the older ampd.jar.
If it's just a warning and nothing's broken, don't worry. I don't mind the message on startup.

> I just built a version which fixes this issue. Version 1.2.9 does not connect to google.
That was fast! Tested and confirmed to be working without any external requests.

**Comment by rain0r** [comment]
> > The music directory is only used to load the album covers, so it's not a big problem if `ampd` can't access it. The whole process playing/browsing music is done via MPD which functions over network. So no worries, if you like, `ampd` can download the covers from MusicBrainz (I see you got that setting active).
> 
> The covers are there, so accessing them locally would be nice, of course. If you can tell me how to produce better log output, there might be a hint on what's going wrong there. Or maybe nfs paths aren't supported at all yet?

Actually I never tried out, if nfs pathe are working. Nevertheless, `musicDirectory` should not be empty if you did specify it. How did you start `ampd`? 
Can you try to set `-Dmpd.music.directory=<path>` to your locally mounted nfs share?  
Also, please use `-Dlogging.level.org.hihn=DEBUG` for a more verbsoe output.

For example

`java -jar -Dmpd.music.directory=/my/nfs/share -Dlogging.level.org.hihn=DEBUG ampd-1.2.9.jar`

**Comment by snflh47** [comment]
I see where this might be coming from. `ampd` does not accept the path as being valid, possibly because there's an issue with the prefix. `mpd` fortunately allows accessing smb and nfs without mounting (thus not requiring root privileges to run or some fstab tinkering) by just prefixing paths `smb://` or `nfs://`. This is part of the documentation at: https://musicpd.org/doc/html/user.html#mounting-other-storages-into-the-music-directory

I tried passing the directory via parameter as you suggested, and we can see it being recognized as "invalid path" with even one of the "/" removed: (I double checked, it's correct in the parameter)

Also: After the first starting up `ampd` and connecting to the web interface, the playlist will be loaded correctly, but according to the log it will still try to connect to MusicBrainz (although i didn't see an outbound connection to their service). So this might just be an incorrect log output:

```
Feb 27 09:46:22 mpd java[1931]: 2021-02-27 09:46:22.430 DEBUG 1931 --- [0.0-8080-exec-3] o.h.a.s.service.CoverFetcherService      : Trying to load a cover of type ALBUM from local cache
Feb 27 09:46:22 mpd java[1931]: 2021-02-27 09:46:22.484 DEBUG 1931 --- [0.0-8080-exec-3] o.h.a.s.service.CoverFetcherService      : Trying to load a cover from the track directory
Feb 27 09:46:22 mpd java[1931]: 2021-02-27 09:46:22.491 ERROR 1931 --- [0.0-8080-exec-3] o.h.a.server.service.CoverCacheService   : No valid path: 'nfs:/servername/shares/audio/dir1/dir2/dir3/file.name'
Feb 27 09:46:22 mpd java[1931]: 2021-02-27 09:46:22.492 DEBUG 1931 --- [0.0-8080-exec-3] o.h.a.s.service.CoverFetcherService      : Trying to load a cover from the MusicBrainz API
```

Later when browsing the library, the log will show entries with paths that have their prefix `nfs://` changed to `nfs:/` - otherwise they would be correct.

`Feb 27 09:46:49 mpd java[1931]: 2021-02-27 09:46:49.221 DEBUG 1931 --- [0.0-8080-exec-7] o.h.a.server.service.CoverCacheService   : No covers found in: nfs:/servername/shares/audio/dir1/dir2/dir3`

The file server's nfs configuration allows unauthenticated access from the client, so there's no authentication issue either (works for `mpd`).

As for starting `ampd`: it's the same behavior when starting in a user session via shell or via systemd. Usually I'm running `ampd` through systemd.

--------------
On a side note: you might want to expand the documentation a little bit (I'm not overly familiar with pull requests etc.) like:

Installation as a service -> systemd

1. Create a user with a home directory (*.jar unpacks data to ~/.m2)
`sudo useradd -m -d /home/ampd ampd`

....

Random thought: I use a symlink to retain the original file names and use the link in my service configuration: `ln -s /opt/ampd/ampd-1.2.9.jar /opt/ampd/ampd-current.jar`

My `ampd.service` also is a bit different, specifying stdout and stderr should be sent to journal, so they can be checked by `journalctl -u ampd -f`

```
[Unit]
Description=ampd

[Service]
User=ampd # <--- Change to a user on your system 

ExecStart=/usr/bin/java \
        -Dmb.cover.service=false \ # <--- remove this line to enable fetching covers from online service
        -jar /opt/ampd/ampd-current.jar # <--- Change to correct path

SuccessExitStatus=143

StandardOutput=journal
StandardError=journal

KillSignal=SIGINT
TimeoutStopSec=20
Restart=always
RestartSec=5
StartLimitInterval=0
StartLimitBurst=10

LimitNOFILE=500000
LimitNPROC=500000

[Install]
WantedBy=multi-user.target
```

**Comment by rain0r** [comment]
To your `nfs` problem:

My understanding of `nfs` is, that you mount shares from the server into your local file system. Like, for example:

    mount 192.168.1.13:/home /media/server 

If you do it like this, you could set `mpd.music.directory` to `/media/server` and `ampd` should be able to load covers from that directory. 

---

>Also: After the first starting up `ampd` and connecting to the web interface, the playlist will be loaded correctly, but according to the log it will still try to connect to MusicBrainz (although i didn't see an outbound connection to their service). So this might just be an incorrect log output:

Yes, the logging was done before the actual check if that setting is active or not. I moved it to the correct place.

---

To the documentation part: 

My goal was to keep the docs as short and simple an possible. It gets you up and running. 
Users who are more familiar with `systemd` might add according statements. And lastly, different people have different preferences: I run `ampd` as my daily user and don't like it to log to the syslog.

**Comment by snflh47** [comment]
> My understanding of `nfs` is, that you mount shares from the server into your local file system. Like, for example:

It's a way, yes. For the `mpd` connection I really like the idea of using the documented way, avoiding all the potential issues that come with mounted file systems (system becoming partly unresponsive if remote filesystem becomes unavailable, fstab, possible permission problems,..). Also keeps the setup a bit simpler, limited to application config (`mpd` + `ampd`). But if it's not supported with `ampd`, that's OK too. I'm aware this is kind of a special use case.

> Yes, the logging was done before the actual check if that setting is active or not. I moved it to the correct place.

Nice!

> To the documentation part:
> 
> My goal was to keep the docs as short and simple an possible. It gets you up and running.
> Users who are more familiar with `systemd` might add according statements. And lastly, different people have different preferences: I run `ampd` as my daily user and don't like it to log to the syslog.

I see your point there. Thought at least I could contribute some docs as I don't have any meaningful programming skills to offer as a thank you for all the work you put into my requests. Never mind then and thanks again!

For what it's worth, I use nginx as reverse proxy, so here's a tested, working configuration with http-to-https redirect that also passes web socket connections.

```
server {
    listen 80;
    server_name ampd.network.local;
    server_name_in_redirect off;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ampd.network.local;
    ssl_certificate /etc/ssl/certs/ampd.network.local.crt;
    ssl_certificate_key /etc/ssl/private/ampd.network.local.key;
    server_name_in_redirect off;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
```

...which of course means: https is now tested and working, so all of the original issues are resolved. Feel free to close this issue any time.

**Comment by rain0r** [comment]
For the NFS part, I'm sorry to disappoint you, but I don't think this will be supported for the immediate future. 

---

Again, thank you very much for input and support! I just added a new file [DEPLOYING.md](https://github.com/rain0r/ampd/blob/master/DEPLOYING.md) with configurations for both Apache and nginx and used your sample.

---

I'm closing the issue for now. Feel free to open another one any time you found a bug, got an idea or just want to contribute to the docs!

**Comment by snflh47** [comment]
DEPLOYING.md - good idea! Just checked it and it has a few issues:

Apache without SSL:
1. Title (`your-server/`) and config (`ServerName localhost`) don't fit. `ServerName` should be `your-server` here or better yet a FQDN.
2. `</If Define>` is closed but not opened

Apache with SSL
1. Virtual host listens to `_default_`? Better allign with the http configuration and use `*:443` instead, no?
2. `ServerName`, see above
3. `RewriteRule` would need to rewrite to `wss://` (WebSocket Secure) in order to use an encrypted connection and not mix encrypted and unencrypted in one setup, if I'm not mistaken.

Nginx without SSL:
1. is no valid config on it's own as this is just a redirect to https, see:  `return 301 https://$server_name$request_uri;` - this would need to be `proxy_pass http://localhost:8080;` as well. My example above is valid as a combination only, as it will listen to 80 and redirect everything to 443 where the correct configuration sits.
2. No web sockets enabled, see config with SSL
