### ISSUE TITLE
Error fetching albums

### ISSUE THREAD

**Issue by MSkaffari** [rain0r/ampd#541]
I run ampd locally and when I click on "Albums" I get the following error and the Albums section is unresponsive

An error occurred
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "http://pi:8080/api/albums",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://pi:8080/api/albums: 500 OK",
  "error": {
    "message": "[2@0] {list} Unknown filter type"
  }
}

**Comment by rain0r** [comment]
Which version of MPD do you use? This error can occur, when the MPD version is too old (for ampd).

**Comment by MSkaffari** [comment]
$ mpd --version
Music Player Daemon 0.21.5 (0.21.5)

**Comment by rain0r** [comment]
This version was released on 22-Feb-2019, maybe you can update MPD an check again?

**Comment by rain0r** [comment]
If this doesn't work with a newer version of MPD, please open an issue.
