### ISSUE TITLE
Error when selectign a genre

### ISSUE THREAD

**Issue by MSkaffari** [rain0r/ampd#542]
The app is able to get the list of all genres but when I try to open any of them I get the following error

An error occurred
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "http://pi:8080/api/genre?genre=Adult%20Alternative%20Pop",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://pi:8080/api/genre?genre=Adult%20Alternative%20Pop: 500 OK",
  "error": {
    "message": "[2@0] {list} Unknown filter type"
  }
}

**Comment by rain0r** [comment]
See my reply in https://github.com/rain0r/ampd/issues/541

**Comment by MSkaffari** [comment]
$ mpd --version
Music Player Daemon 0.21.5 (0.21.5)

**Comment by MSkaffari** [comment]
I'm on raspberrypi and this is the latest I can get. I'll see if I can compile later version myself. Thanks!

**Comment by rain0r** [comment]
Which OS are you using on the Pi?

Did you succeed buliding MPD yourself?

**Comment by MSkaffari** [comment]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


I haven't had the time to try building MPD. I'll update here when I give it a go

**Comment by rain0r** [comment]
If this doesn't work with a newer version of MPD, please open an issue.

**Comment by MSkaffari** [comment]
I finally had some tinkering time and upgraded MPD to 0.23.13 and I still see the samme issue. Same goes for genres and albums

pi@raspberrypi:~ $ mpd --version
Music Player Daemon 0.23.13 (0.23.13)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local


Decoders plugins:
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [pcm]

Filters:


Tag plugins:


Output plugins:
 null fifo pipe oss httpd snapcast recorder

Encoder plugins:
 null wave

Input plugins:
 file

Playlist plugins:
 extm3u m3u pls xspf asx rss cue embcue

Protocols:
 file://

Other features:
 epoll icu inotify ipv6 tcp un

**Comment by rain0r** [comment]
Hey there,

I tried to reproduce the error on the same MPD version (0.23.13) but could not reproduce it.

Could you post the relevant part from your `ampd.log` that contains an error? 

I noticed that you have no `Tag plugins` enabled in your MPD installation. Without `id3tag` I did not get any results under `albums` and `genres`.

After enabling it (with `meson configure output/release -Did3tag=enabled`) I did get results and all functions worked.

Also, your MPD installation is pretty sparse (by design?). Maybe there's an option missing? 

For reference, this is my `mpd.conf`:

```
Music Player Daemon 0.23.13 (0.23.13)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

**Comment by rain0r** [comment]
Much happend since then. 

Please re-open the ticket or create a new one, if the issue still exists.
