### ISSUE TITLE
Add skip forward/reverse buttons.

### ISSUE THREAD

**Issue by leocomitale** [rain0r/ampd#559]
Would it be possible to add skip forward/reverse buttons with a configurable amount of time?  I like to listen to podcasts and it is really annoying not to be able to skip ads.   Right now I am relying on using the position slider but that gets old quick.

**Comment by rain0r** [comment]
Hey there,
yes, that would be definitely possible. 
I will give it a try this week.

**Comment by rain0r** [comment]
Please check out version 1.6.6: https://github.com/rain0r/ampd/releases/tag/ampd-1.6.6

If you set a seek value > 0 in the settings, two additional buttons will appear on the queue view.

Feedback is welcome.

**Comment by rain0r** [comment]
Closing this ticket now.

If something's not working, please create a new one.
