### ISSUE TITLE
Docker build instructions are outdated

### ISSUE THREAD

**Issue by nis65** [rain0r/ampd#603]
Hi, 

I installed yesterday `ampd` on a raspberry Pi. I found the following flaws in the [docker documentation](https://github.com/rain0r/ampd/blob/master/docs/docker.md)

* `docker pull rain0r/ampd` retrieved an x86 binary and not an arm one. Therefore I had to build the image myself
* the first line of the docker file (`FROM openjdk:11-jre-slim`) does not produce a workable image. running the container creates a very generic Java binary incompatibility warning. After some research, I changed this line to (`FROM eclipse-temurin:17-jre-noble`). 

Now it works :-)

**Comment by rain0r** [comment]
You are right! Thank you for the info.

I just updated the docs.
