### ISSUE TITLE
Volume cannot be controlled when music is stopped

### ISSUE THREAD

**Issue by nis65** [rain0r/ampd#604]
I am using ampd V2.0.3 on a Raspberry Pi and I am very happy with it. Thanks for this great program :-)

What I don't understand: When music is stopped, the mpd volume slider is disabled. As soon as it plays, I can lower the volume. To me it is quite natural to check (and usually reduce) the volume **before** I push the play button.

Would this be a small change to achieve or is that an architecture issue?

**Comment by rain0r** [comment]
I just did a check and it seems that will not work.

When retrieving the volume, `mpd` returns an empty response when stopped. That why the slider is not only disabled but also at level 0.

Setting the volume while `mpd` is stopped is not possible, it just ignores the command.

I'm sorry but I think that's not possible.

**Comment by nis65** [comment]
Hhmm. Strange.

When I control my `mpd` with `mpc`, I have:

## playing

~~~
nicolas@kappa2:~$ mpc status
Radio Paradise World-Etc Mix (flac) - playlist: radioparadise.com
[playing] #4/647   0:03/0:00 (0%)
volume: 16%   repeat: off   random: off   single: off   consume: off

nicolas@kappa2:~$ mpc volume 35
Radio Paradise World-Etc Mix (flac) - playlist: radioparadise.com
[playing] #4/647   0:26/0:00 (0%)
volume: 35%   repeat: off   random: off   single: off   consume: off
~~~

## stopped

~~~
nicolas@kappa2:~$ mpc status
volume: 35%   repeat: off   random: off   single: off   consume: off

nicolas@kappa2:~$ mpc volume 60
volume: 60%   repeat: off   random: off   single: off   consume: off
~~~

## mpd version

~~~
nicolas@kappa2:~$ mpc version
mpd version: 0.23.5
~~~

So to me, I can check the volume when stopped and also set it. :thinking:

**Comment by rain0r** [comment]
That's really interesting. I played around a bit and I think it might have something to do with your mixer?

For example, I can't immediately set my volume after `mpc play`:

```sh
$ mpc play && mpc volume 20
The Beatles - A Hard Day’s Night
[playing] #1/1   0:00/2:33 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off
MPD error: Failed to set mixer for 'My Pulse Output'; disconnected
```

But it works with the help of a little `sleep`:

```sh
$ mpc play && sleep 2 && mpc volume 20
The Beatles - A Hard Day’s Night
[playing] #1/1   0:13/2:33 (8%)
volume: 31%   repeat: off   random: off   single: off   consume: off
The Beatles - A Hard Day’s Night
[playing] #1/1   0:15/2:33 (9%)
volume: 20%   repeat: off   random: off   single: off   consume: off
```

Unfortunately, changing the volume during stopped state does not work for me:

```sh
$ mpc stop && sleep 2 && mpc volume 9
volume: n/a   repeat: off   random: off   single: off   consume: off
volume: n/a   repeat: off   random: off   single: off   consume: off
```

Even if I speak directly to the socket:

```sh
$ echo "getvol"  | nc -q 1 localhost 6600
OK MPD 0.23.5
OK
```

Do you mind sharing your `mpd.conf`?

**Comment by nis65** [comment]
Thanks for checking. Here my `mpd.conf`

~~~
connection_timeout      "120"
music_directory         "smb://mysambaserver.local/music"
playlist_directory      "/var/lib/mpd/playlists"
db_file                 "/var/lib/mpd/tag_cache"
pid_file                "/run/mpd/pid"
state_file              "/var/lib/mpd/state"
sticker_file            "/var/lib/mpd/sticker.sql"
user                    "mpd"
bind_to_address         "any"
max_output_buffer_size  "32768"
input {
        plugin "curl"
}
input { 
        plugin "smbclient"
}
input {
       plugin "alsa"
       default_format "44100:16:2"
       auto_resample "no"
       auto_channels "no"
       auto_format "no"
}
audio_output {
        type            "alsa"
        name            "To Snapserver"
        device          "dmix:CARD=Loopback,DEV=0"
        format          "44100:16:2"
        mixer_type      "software"
}
~~~

I assume it is the `mixer_type` that changes the behaviour. In [my setup](/Daenou/ansible-multiroom-audio), I don't let mpd drive the hardware directly but route the audio signal to a `Loopback` device where it is picked up from `snapcast`.

I can imagine that you have `mixer_type "hardware"` in your setup.

**Comment by rain0r** [comment]
Thank you for the info.

My `audio_output` is actually very small:

```
audio_output {
    type        "pulse"
    name        "My Pulse Output"
}
```

I also tried a docker based `mpd` installation with this setup:

```
audio_output {
    type        "httpd"
    name        "MPD HTTP Audio Stream"
    encoder     "lame"      # optional, vorbis or lame
    port        "8000"
    bind_to_address "0.0.0.0"       # optional, IPv4 or IPv6
    bitrate     "320"           # do not define if quality is defined
    max_clients "0"         # optional 0=no limit
    always_on   "yes"
}
```

This setup also yields no information about the volume in a stopped state.

I can't investigate this further and therefore won't implement a solution for this issue but I'm of course open for (working) pull requests.
