### ISSUE TITLE
Reordering playing queue items

### ISSUE THREAD

**Issue by lovrolu** [rain0r/ampd#94]
Hello,

Thanks for the neat project!

A feature request: it would be nice if you could reorder the items in the playing queue just like you can from other MPD clients.

**Comment by rain0r** [comment]
Hi,

that's a great idea, thanks for the input!

I implemted drag&drop for queue tracks and released [ampd-1.3.2](https://github.com/rain0r/ampd/releases/tag/ampd-1.3.2) which contains this feature.

Please let me know if you have any problems with reordering tracks (or in general).

Happy listening!

**Comment by lovrolu** [comment]
That was quick! From the quick couple of tests that I did, everything seems to work.

Thanks!

**Comment by lovrolu** [comment]
This is just a visual thing, but perhaps it would make sense to disable the drag & drop when viewing a particular playlist (under the Browse section). In that case the playlist doesn't actually get modified (which is a good thing) so the UI might be a little misleading.

**Comment by rain0r** [comment]
> This is just a visual thing, but perhaps it would make sense to disable the drag & drop when viewing a particular playlist using the browser. In that case the playlist doesn't actually get modified (which is a good thing) so the UI might be a little misleading.

You're right! It only makes sense on the queue view.

I fixed this in 92e2e7589cc89c55726302fe68cee2207f5784b7.
